### ISSUE TITLE
Implement Framework and all needed Test cases for 3botLogin app

### ISSUE THREAD

**Issue by john-kheir** [3botlogin/3botlogin_testing#1]
- This Story is created to track all the test cases that can be automated for 3botLogin app using mobile-only flow.
- These tasks should for now cover testing the app on Android platform.
- **Appium** will be used as the main framework to automated this test cases with all the required dependencies .

#### Here are the tasks that need to have a test cases for:
- [x] Implement a basic Framework #2 
- [x]  A Registered user can login using the mobile-only flow #3 
- [x] A user registers using the mobile-only flow #4
- [x] Resend verification while registering #9
- [x] Check on preferences page user, email, show phrase and email version info #5
- [x] Change pin code from the preferences page #11 
- [x] Remove account from device #6
- [x] Recover account using wrong name, email and phrase #7 
- [x] Recover account using right info #8
- [x] Recover account using mixed usernames and phrases for the same email #10
- [x] Enable and disable fingerprint #12
